services:
  airflow-postgres:
    image: postgres:15
    container_name: airflow-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    networks:
      - bigdata-net

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    ports:
      - "9870:9870"
    environment:
      CLUSTER_NAME: bigdata-cluster
      CORE_CONF_fs_defaultFS: hdfs://namenode:8020
      HDFS_CONF_dfs_namenode_http_address: 0.0.0.0:9870
    networks:
      - bigdata-net

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    depends_on:
      - namenode
    environment:
      CORE_CONF_fs_defaultFS: hdfs://namenode:8020
    networks:
      - bigdata-net

  spark-master:
    image: apache/spark:3.5.0
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      SPARK_MASTER_HOST: spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    networks:
      - bigdata-net

  spark-worker:
    image: apache/spark:3.5.0
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      SPARK_WORKER_CORES: "2"
      SPARK_WORKER_MEMORY: 1G
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    networks:
      - bigdata-net

  snowflake-mock:
    image: postgres:15
    container_name: snowflake-mock
    environment:
      POSTGRES_USER: snowflake_user
      POSTGRES_PASSWORD: snowflake_pass
      POSTGRES_DB: ECOMMERCE_DWH
    ports:
      - "5433:5432"
    volumes:
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
    networks:
      - bigdata-net

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: j3r9Kt7E1T5m2P8cV4xR6yA0bD5fG9hN1qW3sU6iO8w=
      AIRFLOW__WEBSERVER__SECRET_KEY: my_super_secret_log_key
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "False"
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session
    ports:
      - "8082:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
    command: webserver
    depends_on:
      - airflow-postgres
      - namenode
      - spark-master
    networks:
      - bigdata-net

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow-scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: j3r9Kt7E1T5m2P8cV4xR6yA0bD5fG9hN1qW3sU6iO8w=
      AIRFLOW__WEBSERVER__SECRET_KEY: my_super_secret_log_key
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "False"
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
    command: scheduler
    depends_on:
      - airflow-postgres
      - namenode
      - spark-master
    networks:
      - bigdata-net

networks:
  bigdata-net:
    driver: bridge
